#dangerous-clean-slate: true

name: 🚀 Deploy PNC-Soft-Tech website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: environment variable
        run: echo Hello world $REACT_APP_IMGBB_KEY

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: "ftp.pncsoft.tech"
          username: "pncsofttech@pncsoft.tech"
          # dangerous-clean-slate: true
          password: "fNe(1^rqH5Ae"
          port: 21
          local-dir: ./dist/
